# ~/.config/zsh/zshrc
# Zsh-specific configuration

# Starship configuration
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
export STARSHIP_CACHE=~/.starship/cache
eval "$(starship init zsh)"

eval "$(thefuck --alias)"

# Source the central configuration
if [ -f ~/.config/shell.env ]; then
    source ~/.config/shell.env
fi

# Zsh-specific settings
HISTFILE=~/.config/zsh/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
setopt sharehistory
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_ignore_space
bindkey -e

# Zsh-specific aliases
alias zshconfig='$EDITOR ~/.config/zsh/zshrc'

# Zsh-specific plugins
source $HOME/.config/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $HOME/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
