# ~/.config/bash/bashrc
# Bash-specific configuration

# Starship configuration
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
export STARSHIP_CACHE=~/.starship/cache
eval "$(starship init bash)"

eval "$(thefuck --alias)"

# Source the central configuration
if [ -f ~/.config/shell.env ]; then
    source ~/.config/shell.env
fi

# Bash-specific settings
export HISTCONTROL=ignoreboth
export HISTSIZE=1000
export HISTFILESIZE=2000
shopt -s histappend
shopt -s checkwinsize

# Bash-specific prompt
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
# Bash-specific aliases
alias bashconfig='$EDITOR ~/.config/bash/bashrc'
